name: AsgardEvents
main: com.fivefourdee.asgardevents.AsgardEvents
version: 1.3.1
author: 54D
depend: [Vault]
commands:
   event:
      description: Event related.
      usage: /event
      permission: event.use
      permission-message: Insufficient permissions.
